version: '3.7'

networks:
  traefik:
    name: 'traefik_traefik'
    external: true

services:
  node:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
      target: dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ya.rule=Host(`ya.docker`)"
      - "traefik.docker.network=${TRAEFIK_NETWORK_NAME}"
    volumes:
      - ./:/usr/src/app
    ports:
      - "5173:5173"
    networks:
      - traefik
