export { default as ChatsPage } from './chats/chats'
export { default as LoginPage } from './login/login'
export { default as RegistrationPage } from './registration/registration'
export { default as NavigationPage } from './navigation/navigation'
export { default as ProfilePage } from './profile/profile'
export { default as ProfileSetting } from './profile/settings/setting'
export { default as ProfileChangePassword } from './profile/change-password/change-password'
export { default as ProfileLoadImage } from './profile/load-image/load-image'
export { default as ErrorPage } from './error/error'

